// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/revdbayes.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// any_nonpos
bool any_nonpos(const Rcpp::NumericVector& x);
static SEXP revdbayes_any_nonpos_try(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(any_nonpos(x));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_any_nonpos(SEXP xSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_any_nonpos_try(xSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gp_loglik
double cpp_gp_loglik(const Rcpp::NumericVector& x, const Rcpp::List& ss);
static SEXP revdbayes_cpp_gp_loglik_try(SEXP xSEXP, SEXP ssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ss(ssSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gp_loglik(x, ss));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gp_loglik(SEXP xSEXP, SEXP ssSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gp_loglik_try(xSEXP, ssSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gev_loglik
double cpp_gev_loglik(const Rcpp::NumericVector& x, const Rcpp::List& ss);
static SEXP revdbayes_cpp_gev_loglik_try(SEXP xSEXP, SEXP ssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ss(ssSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gev_loglik(x, ss));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gev_loglik(SEXP xSEXP, SEXP ssSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gev_loglik_try(xSEXP, ssSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// loglik_xptr
SEXP loglik_xptr(std::string fstr);
static SEXP revdbayes_loglik_xptr_try(SEXP fstrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::string >::type fstr(fstrSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_xptr(fstr));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_loglik_xptr(SEXP fstrSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_loglik_xptr_try(fstrSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gp_norm
double cpp_gp_norm(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gp_norm_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gp_norm(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gp_norm(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gp_norm_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gp_mdi
double cpp_gp_mdi(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gp_mdi_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gp_mdi(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gp_mdi(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gp_mdi_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gp_flat
double cpp_gp_flat(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gp_flat_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gp_flat(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gp_flat(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gp_flat_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gp_flatflat
double cpp_gp_flatflat(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gp_flatflat_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gp_flatflat(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gp_flatflat(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gp_flatflat_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gp_jeffreys
double cpp_gp_jeffreys(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gp_jeffreys_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gp_jeffreys(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gp_jeffreys(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gp_jeffreys_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gp_beta
double cpp_gp_beta(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gp_beta_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gp_beta(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gp_beta(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gp_beta_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gev_norm
double cpp_gev_norm(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gev_norm_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gev_norm(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gev_norm(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gev_norm_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gev_loglognorm
double cpp_gev_loglognorm(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gev_loglognorm_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gev_loglognorm(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gev_loglognorm(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gev_loglognorm_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gev_mdi
double cpp_gev_mdi(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gev_mdi_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gev_mdi(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gev_mdi(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gev_mdi_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gev_flat
double cpp_gev_flat(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gev_flat_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gev_flat(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gev_flat(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gev_flat_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gev_flatflat
double cpp_gev_flatflat(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gev_flatflat_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gev_flatflat(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gev_flatflat(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gev_flatflat_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gev_beta
double cpp_gev_beta(const Rcpp::NumericVector& x, const Rcpp::List& ppars);
static SEXP revdbayes_cpp_gev_beta_try(SEXP xSEXP, SEXP pparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ppars(pparsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gev_beta(x, ppars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gev_beta(SEXP xSEXP, SEXP pparsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gev_beta_try(xSEXP, pparsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// logprior_xptr
SEXP logprior_xptr(std::string fstr);
static SEXP revdbayes_logprior_xptr_try(SEXP fstrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::string >::type fstr(fstrSEXP);
    rcpp_result_gen = Rcpp::wrap(logprior_xptr(fstr));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_logprior_xptr(SEXP fstrSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_logprior_xptr_try(fstrSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_logpost
double cpp_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_cpp_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_gp_logpost
double cpp_gp_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_cpp_gp_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gp_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_gp_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_gp_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gp_mdi_logpost
double gp_mdi_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gp_mdi_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gp_mdi_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gp_mdi_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gp_mdi_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gp_norm_logpost
double gp_norm_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gp_norm_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gp_norm_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gp_norm_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gp_norm_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gp_flat_logpost
double gp_flat_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gp_flat_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gp_flat_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gp_flat_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gp_flat_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gp_flatflat_logpost
double gp_flatflat_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gp_flatflat_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gp_flatflat_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gp_flatflat_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gp_flatflat_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gp_jeffreys_logpost
double gp_jeffreys_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gp_jeffreys_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gp_jeffreys_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gp_jeffreys_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gp_jeffreys_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gp_beta_logpost
double gp_beta_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gp_beta_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gp_beta_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gp_beta_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gp_beta_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gev_mdi_logpost
double gev_mdi_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gev_mdi_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gev_mdi_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gev_mdi_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gev_mdi_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gev_norm_logpost
double gev_norm_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gev_norm_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gev_norm_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gev_norm_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gev_norm_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gev_loglognorm_logpost
double gev_loglognorm_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gev_loglognorm_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gev_loglognorm_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gev_loglognorm_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gev_loglognorm_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gev_flat_logpost
double gev_flat_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gev_flat_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gev_flat_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gev_flat_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gev_flat_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gev_flatflat_logpost
double gev_flatflat_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gev_flatflat_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gev_flatflat_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gev_flatflat_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gev_flatflat_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gev_beta_logpost
double gev_beta_logpost(const Rcpp::NumericVector& x, const Rcpp::List& pars);
static SEXP revdbayes_gev_beta_logpost_try(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gev_beta_logpost(x, pars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gev_beta_logpost(SEXP xSEXP, SEXP parsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gev_beta_logpost_try(xSEXP, parsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cpp_logpost_phi
double cpp_logpost_phi(const Rcpp::NumericVector& phi, const Rcpp::List& pars, const SEXP& phi_to_theta_ptr);
static SEXP revdbayes_cpp_logpost_phi_try(SEXP phiSEXP, SEXP parsSEXP, SEXP phi_to_theta_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type phi_to_theta_ptr(phi_to_theta_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_logpost_phi(phi, pars, phi_to_theta_ptr));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_cpp_logpost_phi(SEXP phiSEXP, SEXP parsSEXP, SEXP phi_to_theta_ptrSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_cpp_logpost_phi_try(phiSEXP, parsSEXP, phi_to_theta_ptrSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gp_logpost_xptr
SEXP gp_logpost_xptr(std::string fstr);
static SEXP revdbayes_gp_logpost_xptr_try(SEXP fstrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::string >::type fstr(fstrSEXP);
    rcpp_result_gen = Rcpp::wrap(gp_logpost_xptr(fstr));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gp_logpost_xptr(SEXP fstrSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gp_logpost_xptr_try(fstrSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gev_logpost_xptr
SEXP gev_logpost_xptr(std::string fstr);
static SEXP revdbayes_gev_logpost_xptr_try(SEXP fstrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::string >::type fstr(fstrSEXP);
    rcpp_result_gen = Rcpp::wrap(gev_logpost_xptr(fstr));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gev_logpost_xptr(SEXP fstrSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gev_logpost_xptr_try(fstrSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// gp_phi_to_theta
Rcpp::NumericVector gp_phi_to_theta(const Rcpp::NumericVector& phi, const Rcpp::List& user_args);
static SEXP revdbayes_gp_phi_to_theta_try(SEXP phiSEXP, SEXP user_argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type user_args(user_argsSEXP);
    rcpp_result_gen = Rcpp::wrap(gp_phi_to_theta(phi, user_args));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_gp_phi_to_theta(SEXP phiSEXP, SEXP user_argsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_gp_phi_to_theta_try(phiSEXP, user_argsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// phi_to_theta_xptr
SEXP phi_to_theta_xptr(std::string fstr);
static SEXP revdbayes_phi_to_theta_xptr_try(SEXP fstrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::string >::type fstr(fstrSEXP);
    rcpp_result_gen = Rcpp::wrap(phi_to_theta_xptr(fstr));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP revdbayes_phi_to_theta_xptr(SEXP fstrSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(revdbayes_phi_to_theta_xptr_try(fstrSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int revdbayes_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("bool(*any_nonpos)(const Rcpp::NumericVector&)");
        signatures.insert("double(*cpp_gp_loglik)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gev_loglik)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("SEXP(*loglik_xptr)(std::string)");
        signatures.insert("double(*cpp_gp_norm)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gp_mdi)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gp_flat)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gp_flatflat)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gp_jeffreys)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gp_beta)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gev_norm)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gev_loglognorm)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gev_mdi)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gev_flat)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gev_flatflat)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gev_beta)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("SEXP(*logprior_xptr)(std::string)");
        signatures.insert("double(*cpp_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_gp_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gp_mdi_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gp_norm_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gp_flat_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gp_flatflat_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gp_jeffreys_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gp_beta_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gev_mdi_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gev_norm_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gev_loglognorm_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gev_flat_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gev_flatflat_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*gev_beta_logpost)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("double(*cpp_logpost_phi)(const Rcpp::NumericVector&,const Rcpp::List&,const SEXP&)");
        signatures.insert("SEXP(*gp_logpost_xptr)(std::string)");
        signatures.insert("SEXP(*gev_logpost_xptr)(std::string)");
        signatures.insert("Rcpp::NumericVector(*gp_phi_to_theta)(const Rcpp::NumericVector&,const Rcpp::List&)");
        signatures.insert("SEXP(*phi_to_theta_xptr)(std::string)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP revdbayes_RcppExport_registerCCallable() { 
    R_RegisterCCallable("revdbayes", "revdbayes_any_nonpos", (DL_FUNC)revdbayes_any_nonpos_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gp_loglik", (DL_FUNC)revdbayes_cpp_gp_loglik_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gev_loglik", (DL_FUNC)revdbayes_cpp_gev_loglik_try);
    R_RegisterCCallable("revdbayes", "revdbayes_loglik_xptr", (DL_FUNC)revdbayes_loglik_xptr_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gp_norm", (DL_FUNC)revdbayes_cpp_gp_norm_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gp_mdi", (DL_FUNC)revdbayes_cpp_gp_mdi_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gp_flat", (DL_FUNC)revdbayes_cpp_gp_flat_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gp_flatflat", (DL_FUNC)revdbayes_cpp_gp_flatflat_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gp_jeffreys", (DL_FUNC)revdbayes_cpp_gp_jeffreys_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gp_beta", (DL_FUNC)revdbayes_cpp_gp_beta_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gev_norm", (DL_FUNC)revdbayes_cpp_gev_norm_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gev_loglognorm", (DL_FUNC)revdbayes_cpp_gev_loglognorm_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gev_mdi", (DL_FUNC)revdbayes_cpp_gev_mdi_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gev_flat", (DL_FUNC)revdbayes_cpp_gev_flat_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gev_flatflat", (DL_FUNC)revdbayes_cpp_gev_flatflat_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gev_beta", (DL_FUNC)revdbayes_cpp_gev_beta_try);
    R_RegisterCCallable("revdbayes", "revdbayes_logprior_xptr", (DL_FUNC)revdbayes_logprior_xptr_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_logpost", (DL_FUNC)revdbayes_cpp_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_gp_logpost", (DL_FUNC)revdbayes_cpp_gp_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gp_mdi_logpost", (DL_FUNC)revdbayes_gp_mdi_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gp_norm_logpost", (DL_FUNC)revdbayes_gp_norm_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gp_flat_logpost", (DL_FUNC)revdbayes_gp_flat_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gp_flatflat_logpost", (DL_FUNC)revdbayes_gp_flatflat_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gp_jeffreys_logpost", (DL_FUNC)revdbayes_gp_jeffreys_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gp_beta_logpost", (DL_FUNC)revdbayes_gp_beta_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gev_mdi_logpost", (DL_FUNC)revdbayes_gev_mdi_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gev_norm_logpost", (DL_FUNC)revdbayes_gev_norm_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gev_loglognorm_logpost", (DL_FUNC)revdbayes_gev_loglognorm_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gev_flat_logpost", (DL_FUNC)revdbayes_gev_flat_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gev_flatflat_logpost", (DL_FUNC)revdbayes_gev_flatflat_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gev_beta_logpost", (DL_FUNC)revdbayes_gev_beta_logpost_try);
    R_RegisterCCallable("revdbayes", "revdbayes_cpp_logpost_phi", (DL_FUNC)revdbayes_cpp_logpost_phi_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gp_logpost_xptr", (DL_FUNC)revdbayes_gp_logpost_xptr_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gev_logpost_xptr", (DL_FUNC)revdbayes_gev_logpost_xptr_try);
    R_RegisterCCallable("revdbayes", "revdbayes_gp_phi_to_theta", (DL_FUNC)revdbayes_gp_phi_to_theta_try);
    R_RegisterCCallable("revdbayes", "revdbayes_phi_to_theta_xptr", (DL_FUNC)revdbayes_phi_to_theta_xptr_try);
    R_RegisterCCallable("revdbayes", "revdbayes_RcppExport_validate", (DL_FUNC)revdbayes_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"revdbayes_any_nonpos", (DL_FUNC) &revdbayes_any_nonpos, 1},
    {"revdbayes_cpp_gp_loglik", (DL_FUNC) &revdbayes_cpp_gp_loglik, 2},
    {"revdbayes_cpp_gev_loglik", (DL_FUNC) &revdbayes_cpp_gev_loglik, 2},
    {"revdbayes_loglik_xptr", (DL_FUNC) &revdbayes_loglik_xptr, 1},
    {"revdbayes_cpp_gp_norm", (DL_FUNC) &revdbayes_cpp_gp_norm, 2},
    {"revdbayes_cpp_gp_mdi", (DL_FUNC) &revdbayes_cpp_gp_mdi, 2},
    {"revdbayes_cpp_gp_flat", (DL_FUNC) &revdbayes_cpp_gp_flat, 2},
    {"revdbayes_cpp_gp_flatflat", (DL_FUNC) &revdbayes_cpp_gp_flatflat, 2},
    {"revdbayes_cpp_gp_jeffreys", (DL_FUNC) &revdbayes_cpp_gp_jeffreys, 2},
    {"revdbayes_cpp_gp_beta", (DL_FUNC) &revdbayes_cpp_gp_beta, 2},
    {"revdbayes_cpp_gev_norm", (DL_FUNC) &revdbayes_cpp_gev_norm, 2},
    {"revdbayes_cpp_gev_loglognorm", (DL_FUNC) &revdbayes_cpp_gev_loglognorm, 2},
    {"revdbayes_cpp_gev_mdi", (DL_FUNC) &revdbayes_cpp_gev_mdi, 2},
    {"revdbayes_cpp_gev_flat", (DL_FUNC) &revdbayes_cpp_gev_flat, 2},
    {"revdbayes_cpp_gev_flatflat", (DL_FUNC) &revdbayes_cpp_gev_flatflat, 2},
    {"revdbayes_cpp_gev_beta", (DL_FUNC) &revdbayes_cpp_gev_beta, 2},
    {"revdbayes_logprior_xptr", (DL_FUNC) &revdbayes_logprior_xptr, 1},
    {"revdbayes_cpp_logpost", (DL_FUNC) &revdbayes_cpp_logpost, 2},
    {"revdbayes_cpp_gp_logpost", (DL_FUNC) &revdbayes_cpp_gp_logpost, 2},
    {"revdbayes_gp_mdi_logpost", (DL_FUNC) &revdbayes_gp_mdi_logpost, 2},
    {"revdbayes_gp_norm_logpost", (DL_FUNC) &revdbayes_gp_norm_logpost, 2},
    {"revdbayes_gp_flat_logpost", (DL_FUNC) &revdbayes_gp_flat_logpost, 2},
    {"revdbayes_gp_flatflat_logpost", (DL_FUNC) &revdbayes_gp_flatflat_logpost, 2},
    {"revdbayes_gp_jeffreys_logpost", (DL_FUNC) &revdbayes_gp_jeffreys_logpost, 2},
    {"revdbayes_gp_beta_logpost", (DL_FUNC) &revdbayes_gp_beta_logpost, 2},
    {"revdbayes_gev_mdi_logpost", (DL_FUNC) &revdbayes_gev_mdi_logpost, 2},
    {"revdbayes_gev_norm_logpost", (DL_FUNC) &revdbayes_gev_norm_logpost, 2},
    {"revdbayes_gev_loglognorm_logpost", (DL_FUNC) &revdbayes_gev_loglognorm_logpost, 2},
    {"revdbayes_gev_flat_logpost", (DL_FUNC) &revdbayes_gev_flat_logpost, 2},
    {"revdbayes_gev_flatflat_logpost", (DL_FUNC) &revdbayes_gev_flatflat_logpost, 2},
    {"revdbayes_gev_beta_logpost", (DL_FUNC) &revdbayes_gev_beta_logpost, 2},
    {"revdbayes_cpp_logpost_phi", (DL_FUNC) &revdbayes_cpp_logpost_phi, 3},
    {"revdbayes_gp_logpost_xptr", (DL_FUNC) &revdbayes_gp_logpost_xptr, 1},
    {"revdbayes_gev_logpost_xptr", (DL_FUNC) &revdbayes_gev_logpost_xptr, 1},
    {"revdbayes_gp_phi_to_theta", (DL_FUNC) &revdbayes_gp_phi_to_theta, 2},
    {"revdbayes_phi_to_theta_xptr", (DL_FUNC) &revdbayes_phi_to_theta_xptr, 1},
    {"revdbayes_RcppExport_registerCCallable", (DL_FUNC) &revdbayes_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_revdbayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
