# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_gp_loglik <- function(x, ss) {
    .Call('revdbayes_cpp_gp_loglik', PACKAGE = 'revdbayes', x, ss)
}

#' Create external pointer to a C++ log-likelihood function
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
loglik_xptr <- function(fstr) {
    .Call('revdbayes_loglik_xptr', PACKAGE = 'revdbayes', fstr)
}

cpp_gp_mdi <- function(x, ppars) {
    .Call('revdbayes_cpp_gp_mdi', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_flat <- function(x, ppars) {
    .Call('revdbayes_cpp_gp_flat', PACKAGE = 'revdbayes', x, ppars)
}

#' Create external pointer to a C++ prior function
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
logprior_xptr <- function(fstr) {
    .Call('revdbayes_logprior_xptr', PACKAGE = 'revdbayes', fstr)
}

cpp_logpost <- function(x, pars) {
    .Call('revdbayes_cpp_logpost', PACKAGE = 'revdbayes', x, pars)
}

#' Create external pointer to a C++ log-posterior function
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
logpost_xptr <- function(fstr) {
    .Call('revdbayes_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

gp_phi_to_theta <- function(phi, user_args) {
    .Call('revdbayes_gp_phi_to_theta', PACKAGE = 'revdbayes', phi, user_args)
}

#' Create external pointer to a C++ phi_to_theta function
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
phi_to_theta_xptr <- function(fstr) {
    .Call('revdbayes_phi_to_theta_xptr', PACKAGE = 'revdbayes', fstr)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('revdbayes_RcppExport_registerCCallable', PACKAGE = 'revdbayes')
})
