# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

any_nonpos <- function(x) {
    .Call('_revdbayes_any_nonpos', PACKAGE = 'revdbayes', x)
}

cpp_gp_loglik <- function(x, ss) {
    .Call('_revdbayes_cpp_gp_loglik', PACKAGE = 'revdbayes', x, ss)
}

cpp_gev_loglik <- function(x, ss) {
    .Call('_revdbayes_cpp_gev_loglik', PACKAGE = 'revdbayes', x, ss)
}

cpp_os_loglik <- function(x, ss) {
    .Call('_revdbayes_cpp_os_loglik', PACKAGE = 'revdbayes', x, ss)
}

cpp_pp_loglik <- function(x, ss) {
    .Call('_revdbayes_cpp_pp_loglik', PACKAGE = 'revdbayes', x, ss)
}

cpp_gp_norm <- function(x, ppars) {
    .Call('_revdbayes_cpp_gp_norm', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_mdi <- function(x, ppars) {
    .Call('_revdbayes_cpp_gp_mdi', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_flat <- function(x, ppars) {
    .Call('_revdbayes_cpp_gp_flat', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_flatflat <- function(x, ppars) {
    .Call('_revdbayes_cpp_gp_flatflat', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_jeffreys <- function(x, ppars) {
    .Call('_revdbayes_cpp_gp_jeffreys', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_beta <- function(x, ppars) {
    .Call('_revdbayes_cpp_gp_beta', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_norm <- function(x, ppars) {
    .Call('_revdbayes_cpp_gev_norm', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_loglognorm <- function(x, ppars) {
    .Call('_revdbayes_cpp_gev_loglognorm', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_mdi <- function(x, ppars) {
    .Call('_revdbayes_cpp_gev_mdi', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_flat <- function(x, ppars) {
    .Call('_revdbayes_cpp_gev_flat', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_flatflat <- function(x, ppars) {
    .Call('_revdbayes_cpp_gev_flatflat', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_beta <- function(x, ppars) {
    .Call('_revdbayes_cpp_gev_beta', PACKAGE = 'revdbayes', x, ppars)
}

lgdgev_cpp <- function(x, loc, scale, shape) {
    .Call('_revdbayes_lgdgev_cpp', PACKAGE = 'revdbayes', x, loc, scale, shape)
}

pgev_cpp <- function(q, loc, scale, shape) {
    .Call('_revdbayes_pgev_cpp', PACKAGE = 'revdbayes', q, loc, scale, shape)
}

qgev_cpp <- function(p, loc, scale, shape) {
    .Call('_revdbayes_qgev_cpp', PACKAGE = 'revdbayes', p, loc, scale, shape)
}

cpp_gev_prob <- function(x, ppars) {
    .Call('_revdbayes_cpp_gev_prob', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_quant <- function(x, ppars) {
    .Call('_revdbayes_cpp_gev_quant', PACKAGE = 'revdbayes', x, ppars)
}

gp_user_logpost <- function(x, pars) {
    .Call('_revdbayes_gp_user_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_user_logpost <- function(x, pars) {
    .Call('_revdbayes_gev_user_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_user_logpost <- function(x, pars) {
    .Call('_revdbayes_os_user_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_user_logpost <- function(x, pars) {
    .Call('_revdbayes_pp_user_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_mdi_logpost <- function(x, pars) {
    .Call('_revdbayes_gp_mdi_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_norm_logpost <- function(x, pars) {
    .Call('_revdbayes_gp_norm_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_flat_logpost <- function(x, pars) {
    .Call('_revdbayes_gp_flat_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_flatflat_logpost <- function(x, pars) {
    .Call('_revdbayes_gp_flatflat_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_jeffreys_logpost <- function(x, pars) {
    .Call('_revdbayes_gp_jeffreys_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_beta_logpost <- function(x, pars) {
    .Call('_revdbayes_gp_beta_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_mdi_logpost <- function(x, pars) {
    .Call('_revdbayes_gev_mdi_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_norm_logpost <- function(x, pars) {
    .Call('_revdbayes_gev_norm_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_loglognorm_logpost <- function(x, pars) {
    .Call('_revdbayes_gev_loglognorm_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_flat_logpost <- function(x, pars) {
    .Call('_revdbayes_gev_flat_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_flatflat_logpost <- function(x, pars) {
    .Call('_revdbayes_gev_flatflat_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_beta_logpost <- function(x, pars) {
    .Call('_revdbayes_gev_beta_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_prob_logpost <- function(x, pars) {
    .Call('_revdbayes_gev_prob_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_quant_logpost <- function(x, pars) {
    .Call('_revdbayes_gev_quant_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_mdi_logpost <- function(x, pars) {
    .Call('_revdbayes_pp_mdi_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_norm_logpost <- function(x, pars) {
    .Call('_revdbayes_pp_norm_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_loglognorm_logpost <- function(x, pars) {
    .Call('_revdbayes_pp_loglognorm_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_flat_logpost <- function(x, pars) {
    .Call('_revdbayes_pp_flat_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_flatflat_logpost <- function(x, pars) {
    .Call('_revdbayes_pp_flatflat_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_beta_logpost <- function(x, pars) {
    .Call('_revdbayes_pp_beta_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_prob_logpost <- function(x, pars) {
    .Call('_revdbayes_pp_prob_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_quant_logpost <- function(x, pars) {
    .Call('_revdbayes_pp_quant_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_mdi_logpost <- function(x, pars) {
    .Call('_revdbayes_os_mdi_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_norm_logpost <- function(x, pars) {
    .Call('_revdbayes_os_norm_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_loglognorm_logpost <- function(x, pars) {
    .Call('_revdbayes_os_loglognorm_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_flat_logpost <- function(x, pars) {
    .Call('_revdbayes_os_flat_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_flatflat_logpost <- function(x, pars) {
    .Call('_revdbayes_os_flatflat_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_beta_logpost <- function(x, pars) {
    .Call('_revdbayes_os_beta_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_prob_logpost <- function(x, pars) {
    .Call('_revdbayes_os_prob_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_quant_logpost <- function(x, pars) {
    .Call('_revdbayes_os_quant_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_logpost_xptr <- function(fstr) {
    .Call('_revdbayes_gp_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

gev_logpost_xptr <- function(fstr) {
    .Call('_revdbayes_gev_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

os_logpost_xptr <- function(fstr) {
    .Call('_revdbayes_os_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

pp_logpost_xptr <- function(fstr) {
    .Call('_revdbayes_pp_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

gp_phi_to_theta <- function(phi, user_args) {
    .Call('_revdbayes_gp_phi_to_theta', PACKAGE = 'revdbayes', phi, user_args)
}

gev_phi_to_theta <- function(phi, user_args) {
    .Call('_revdbayes_gev_phi_to_theta', PACKAGE = 'revdbayes', phi, user_args)
}

pp_phi_to_theta <- function(phi, user_args) {
    .Call('_revdbayes_pp_phi_to_theta', PACKAGE = 'revdbayes', phi, user_args)
}

kgaps_phi_to_theta <- function(phi, user_args) {
    .Call('_revdbayes_kgaps_phi_to_theta', PACKAGE = 'revdbayes', phi, user_args)
}

phi_to_theta_xptr <- function(fstr) {
    .Call('_revdbayes_phi_to_theta_xptr', PACKAGE = 'revdbayes', fstr)
}

gp_mdi_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gp_mdi_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gp_norm_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gp_norm_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gp_flat_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gp_flat_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gp_flatflat_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gp_flatflat_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gp_jeffreys_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gp_jeffreys_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gp_beta_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gp_beta_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gp_user_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gp_user_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gev_mdi_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gev_mdi_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gev_norm_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gev_norm_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gev_loglognorm_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gev_loglognorm_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gev_flat_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gev_flat_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gev_flatflat_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gev_flatflat_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gev_beta_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gev_beta_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gev_prob_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gev_prob_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gev_quant_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gev_quant_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gev_user_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_gev_user_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

os_mdi_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_os_mdi_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

os_norm_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_os_norm_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

os_loglognorm_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_os_loglognorm_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

os_flat_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_os_flat_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

os_flatflat_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_os_flatflat_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

os_beta_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_os_beta_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

os_prob_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_os_prob_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

os_quant_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_os_quant_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

os_user_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_os_user_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

pp_mdi_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_pp_mdi_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

pp_norm_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_pp_norm_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

pp_loglognorm_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_pp_loglognorm_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

pp_flat_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_pp_flat_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

pp_flatflat_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_pp_flatflat_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

pp_beta_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_pp_beta_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

pp_prob_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_pp_prob_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

pp_quant_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_pp_quant_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

pp_user_logpost_phi <- function(phi, pars) {
    .Call('_revdbayes_pp_user_logpost_phi', PACKAGE = 'revdbayes', phi, pars)
}

gp_logpost_phi_xptr <- function(fstr) {
    .Call('_revdbayes_gp_logpost_phi_xptr', PACKAGE = 'revdbayes', fstr)
}

gev_logpost_phi_xptr <- function(fstr) {
    .Call('_revdbayes_gev_logpost_phi_xptr', PACKAGE = 'revdbayes', fstr)
}

pp_logpost_phi_xptr <- function(fstr) {
    .Call('_revdbayes_pp_logpost_phi_xptr', PACKAGE = 'revdbayes', fstr)
}

os_logpost_phi_xptr <- function(fstr) {
    .Call('_revdbayes_os_logpost_phi_xptr', PACKAGE = 'revdbayes', fstr)
}

kgaps_logpost <- function(x, pars) {
    .Call('_revdbayes_kgaps_logpost', PACKAGE = 'revdbayes', x, pars)
}

kgaps_logpost_xptr <- function(fstr) {
    .Call('_revdbayes_kgaps_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

kgaps_log_j <- function(theta, user_args) {
    .Call('_revdbayes_kgaps_log_j', PACKAGE = 'revdbayes', theta, user_args)
}

log_j_xptr <- function(fstr) {
    .Call('_revdbayes_log_j_xptr', PACKAGE = 'revdbayes', fstr)
}

user_gp_flat <- function(x, ppars) {
    .Call('_revdbayes_user_gp_flat', PACKAGE = 'revdbayes', x, ppars)
}

user_gev_norm <- function(x, ppars) {
    .Call('_revdbayes_user_gev_norm', PACKAGE = 'revdbayes', x, ppars)
}

user_gev_flat <- function(x, ppars) {
    .Call('_revdbayes_user_gev_flat', PACKAGE = 'revdbayes', x, ppars)
}

#' Create an external pointer to a C++ prior
#'
#' This function provides an example of a way in which a user can specify
#' their own prior density to \code{\link{rpost_rcpp}}.
#' More specifically, a function like this (the user will need to create
#' an edited version tailored to their own C++ function(s)) can be used to
#' generate an external pointer to a compiled C++ function that evaluates
#' the log-prior density.  Please see the vignette
#' "Faster simulation using revdbayes" for more information.
#'
#' @details
#' Suppose that the user's C++ functions are in a file called "user_fns.cpp".
#' These functions must be compiled and made available to R before the
#' pointer is created. This can be achieved using the function
#' \code{\link[Rcpp]{sourceCpp}} in the \strong{Rcpp} package
#' or using RStudio's Source button on the editor toolbar.
#'
#' For details see the examples in the documentation of the functions
#' \code{\link{rpost_rcpp}} and \code{\link{set_prior}},
#' the vignette "Faster simulation using revdbayes"
#' and the vignette "Rusting Faster: Simulation using Rcpp" in the package
#' \strong{rust}.
#'
#' @param fstr A string indicating the C++ function required.
#' @return An external pointer.
#' @seealso \code{\link{set_prior}} to specify a prior distribution using
#'   an external pointer returned by \code{create_prior_xptr} and for
#'   details of in-built named prior distributions.
#' @seealso The examples in the documentation of \code{\link{rpost_rcpp}}.
#' @examples
#' ptr_gp_flat <- create_prior_xptr("gp_flat")
#' prior_cfn <- set_prior(prior = ptr_gp_flat, model = "gp", min_xi = -1)
#'
#' ptr_gev_flat <- create_prior_xptr("gev_flat")
#' prior_cfn <- set_prior(prior = ptr_gev_flat, model = "gev", min_xi = -1,
#'                        max_xi = Inf)
#'
#' mat <- diag(c(10000, 10000, 100))
#' ptr_gev_norm <- create_prior_xptr("gev_norm")
#' pn_u <- set_prior(prior = ptr_gev_norm, model = "gev", mean = c(0,0,0),
#'                   icov = solve(mat))
#' @export
create_prior_xptr <- function(fstr) {
    .Call('_revdbayes_create_prior_xptr', PACKAGE = 'revdbayes', fstr)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_revdbayes_RcppExport_registerCCallable', PACKAGE = 'revdbayes')
})
