# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

any_nonpos <- function(x) {
    .Call('revdbayes_any_nonpos', PACKAGE = 'revdbayes', x)
}

cpp_gp_loglik <- function(x, ss) {
    .Call('revdbayes_cpp_gp_loglik', PACKAGE = 'revdbayes', x, ss)
}

cpp_gev_loglik <- function(x, ss) {
    .Call('revdbayes_cpp_gev_loglik', PACKAGE = 'revdbayes', x, ss)
}

cpp_os_loglik <- function(x, ss) {
    .Call('revdbayes_cpp_os_loglik', PACKAGE = 'revdbayes', x, ss)
}

cpp_pp_loglik <- function(x, ss) {
    .Call('revdbayes_cpp_pp_loglik', PACKAGE = 'revdbayes', x, ss)
}

cpp_gp_norm <- function(x, ppars) {
    .Call('revdbayes_cpp_gp_norm', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_mdi <- function(x, ppars) {
    .Call('revdbayes_cpp_gp_mdi', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_flat <- function(x, ppars) {
    .Call('revdbayes_cpp_gp_flat', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_flatflat <- function(x, ppars) {
    .Call('revdbayes_cpp_gp_flatflat', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_jeffreys <- function(x, ppars) {
    .Call('revdbayes_cpp_gp_jeffreys', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gp_beta <- function(x, ppars) {
    .Call('revdbayes_cpp_gp_beta', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_norm <- function(x, ppars) {
    .Call('revdbayes_cpp_gev_norm', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_loglognorm <- function(x, ppars) {
    .Call('revdbayes_cpp_gev_loglognorm', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_mdi <- function(x, ppars) {
    .Call('revdbayes_cpp_gev_mdi', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_flat <- function(x, ppars) {
    .Call('revdbayes_cpp_gev_flat', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_flatflat <- function(x, ppars) {
    .Call('revdbayes_cpp_gev_flatflat', PACKAGE = 'revdbayes', x, ppars)
}

cpp_gev_beta <- function(x, ppars) {
    .Call('revdbayes_cpp_gev_beta', PACKAGE = 'revdbayes', x, ppars)
}

cpp_logpost <- function(x, pars) {
    .Call('revdbayes_cpp_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_user_logpost <- function(x, pars) {
    .Call('revdbayes_gp_user_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_user_logpost <- function(x, pars) {
    .Call('revdbayes_gev_user_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_user_logpost <- function(x, pars) {
    .Call('revdbayes_os_user_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_user_logpost <- function(x, pars) {
    .Call('revdbayes_pp_user_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_mdi_logpost <- function(x, pars) {
    .Call('revdbayes_gp_mdi_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_norm_logpost <- function(x, pars) {
    .Call('revdbayes_gp_norm_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_flat_logpost <- function(x, pars) {
    .Call('revdbayes_gp_flat_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_flatflat_logpost <- function(x, pars) {
    .Call('revdbayes_gp_flatflat_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_jeffreys_logpost <- function(x, pars) {
    .Call('revdbayes_gp_jeffreys_logpost', PACKAGE = 'revdbayes', x, pars)
}

gp_beta_logpost <- function(x, pars) {
    .Call('revdbayes_gp_beta_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_mdi_logpost <- function(x, pars) {
    .Call('revdbayes_gev_mdi_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_norm_logpost <- function(x, pars) {
    .Call('revdbayes_gev_norm_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_loglognorm_logpost <- function(x, pars) {
    .Call('revdbayes_gev_loglognorm_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_flat_logpost <- function(x, pars) {
    .Call('revdbayes_gev_flat_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_flatflat_logpost <- function(x, pars) {
    .Call('revdbayes_gev_flatflat_logpost', PACKAGE = 'revdbayes', x, pars)
}

gev_beta_logpost <- function(x, pars) {
    .Call('revdbayes_gev_beta_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_mdi_logpost <- function(x, pars) {
    .Call('revdbayes_pp_mdi_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_norm_logpost <- function(x, pars) {
    .Call('revdbayes_pp_norm_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_loglognorm_logpost <- function(x, pars) {
    .Call('revdbayes_pp_loglognorm_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_flat_logpost <- function(x, pars) {
    .Call('revdbayes_pp_flat_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_flatflat_logpost <- function(x, pars) {
    .Call('revdbayes_pp_flatflat_logpost', PACKAGE = 'revdbayes', x, pars)
}

pp_beta_logpost <- function(x, pars) {
    .Call('revdbayes_pp_beta_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_mdi_logpost <- function(x, pars) {
    .Call('revdbayes_os_mdi_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_norm_logpost <- function(x, pars) {
    .Call('revdbayes_os_norm_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_loglognorm_logpost <- function(x, pars) {
    .Call('revdbayes_os_loglognorm_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_flat_logpost <- function(x, pars) {
    .Call('revdbayes_os_flat_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_flatflat_logpost <- function(x, pars) {
    .Call('revdbayes_os_flatflat_logpost', PACKAGE = 'revdbayes', x, pars)
}

os_beta_logpost <- function(x, pars) {
    .Call('revdbayes_os_beta_logpost', PACKAGE = 'revdbayes', x, pars)
}

cpp_logpost_phi <- function(phi, pars, phi_to_theta_ptr) {
    .Call('revdbayes_cpp_logpost_phi', PACKAGE = 'revdbayes', phi, pars, phi_to_theta_ptr)
}

#' Create external pointer to a C++ GP log-posterior function
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
gp_logpost_xptr <- function(fstr) {
    .Call('revdbayes_gp_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

#' Create external pointer to a C++ GEV log-posterior function
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
gev_logpost_xptr <- function(fstr) {
    .Call('revdbayes_gev_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

#' Create external pointer to a C++ OS log-posterior function
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
os_logpost_xptr <- function(fstr) {
    .Call('revdbayes_os_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

#' Create external pointer to a C++ PP log-posterior function
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
pp_logpost_xptr <- function(fstr) {
    .Call('revdbayes_pp_logpost_xptr', PACKAGE = 'revdbayes', fstr)
}

gp_phi_to_theta <- function(phi, user_args) {
    .Call('revdbayes_gp_phi_to_theta', PACKAGE = 'revdbayes', phi, user_args)
}

#' Create external pointer to a C++ phi_to_theta function
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
phi_to_theta_xptr <- function(fstr) {
    .Call('revdbayes_phi_to_theta_xptr', PACKAGE = 'revdbayes', fstr)
}

user_gp_flat <- function(x, ppars) {
    .Call('revdbayes_user_gp_flat', PACKAGE = 'revdbayes', x, ppars)
}

user_gev_norm <- function(x, ppars) {
    .Call('revdbayes_user_gev_norm', PACKAGE = 'revdbayes', x, ppars)
}

user_gev_flat <- function(x, ppars) {
    .Call('revdbayes_user_gev_flat', PACKAGE = 'revdbayes', x, ppars)
}

#' Create external pointer to a C++ function for a log-prior
#'
#' @param fstr A string indicating the C++ function required.
#'
#' @export
create_prior_xptr <- function(fstr) {
    .Call('revdbayes_create_prior_xptr', PACKAGE = 'revdbayes', fstr)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('revdbayes_RcppExport_registerCCallable', PACKAGE = 'revdbayes')
})
